### ISSUE TITLE
IntuneAppCleaner Processor Fails

### ISSUE THREAD

**Issue by kdrwygvh** [almenscorner/intune-uploader#12]
When testing the IntuneAppCleaner processor I get the following error back from Python:

`Error in local.intune.Code: Processor: com.github.almenscorner.intune-upload.processors/IntuneAppCleaner: Error: '>' not supported between instances of 'int' and 'str'`

**Comment by almenscorner** [comment]
Can you send the command you're running?

**Comment by almenscorner** [comment]
verbose output from the run would also be helpful

**Comment by kdrwygvh** [comment]
`autopkg run -v --post com.github.almenscorner.intune-upload.processors/IntuneAppCleaner -k display_name="Visual Studio Code" -k keep_version_count=1 Code.intune.recipe
Processing Code.intune.recipe...
URLDownloader
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/john/Library/AutoPkg/Cache/local.intune.Code/downloads/vscode.zip
EndOfCheckPhase
Unarchiver
Unarchiver: Guessed archive format 'zip' from filename vscode.zip
Unarchiver: Unarchived /Users/john/Library/AutoPkg/Cache/local.intune.Code/downloads/vscode.zip to /Users/john/Library/AutoPkg/Cache/local.intune.Code/VSCode
CodeSignatureVerifier
CodeSignatureVerifier: Verifying code signature...
CodeSignatureVerifier: Deep verification enabled...
CodeSignatureVerifier: Strict verification not defined. Using codesign defaults...
CodeSignatureVerifier: /Users/john/Library/AutoPkg/Cache/local.intune.Code/VSCode/Visual Studio Code.app: valid on disk
CodeSignatureVerifier: /Users/john/Library/AutoPkg/Cache/local.intune.Code/VSCode/Visual Studio Code.app: satisfies its Designated Requirement
CodeSignatureVerifier: /Users/john/Library/AutoPkg/Cache/local.intune.Code/VSCode/Visual Studio Code.app: explicit requirement satisfied
CodeSignatureVerifier: Signature is valid
Versioner
Versioner: Found version 1.87.0 in file /Users/john/Library/AutoPkg/Cache/local.intune.Code/VSCode/Visual Studio Code.app/Contents/Info.plist
DmgCreator
DmgCreator: Created dmg from /Users/john/Library/AutoPkg/Cache/local.intune.Code/VSCode at /Users/john/Library/AutoPkg/Cache/local.intune.Code/VSCode.dmg
AppDmgVersioner
AppDmgVersioner: Mounted disk image /Users/john/Library/AutoPkg/Cache/local.intune.Code/VSCode.dmg
AppDmgVersioner: BundleID: com.microsoft.VSCode
AppDmgVersioner: Version: 1.87.0
com.github.almenscorner.intune-upload.processors/IntuneAppIconGetter
com.github.almenscorner.intune-upload.processors/IntuneAppUploader
IntuneAppUploader: App Visual Studio Code version 1.87.0 is up to date
com.github.almenscorner.intune-upload.processors/IntuneAppCleaner
IntuneAppCleaner: Found 2 apps matching Visual Studio Code
'>' not supported between instances of 'int' and 'str'
Failed.
Receipt written to /Users/john/Library/AutoPkg/Cache/local.intune.Code/receipts/Code.intune-receipt-20240229-122813.plist

The following recipes failed:
    Code.intune.recipe
        Error in local.intune.Code: Processor: com.github.almenscorner.intune-upload.processors/IntuneAppCleaner: Error: '>' not supported between instances of 'int' and 'str'

Nothing downloaded, packaged or imported.
`

**Comment by almenscorner** [comment]
A bug found its way in during re-factoring which meant it did not convert the str to an int. It has been fixed and you should be able to run after updating the repo.

**Comment by kdrwygvh** [comment]
Fix verified. Many thanks.
