### ISSUE TITLE
install as managed not supported

### ISSUE THREAD

**Issue by drviper75** [almenscorner/intune-uploader#4]
Since the latest IntuneAppUploader.py it is not possible to upload a pkg as "Install-as-managed", i´m not sure if it works in the old version.

[#microsoft.graph.macOSPkgApp](https://learn.microsoft.com/en-us/graph/api/intune-apps-macospkgapp-create?view=graph-rest-beta) and [#microsoft.graph.macOSDmgApp](https://learn.microsoft.com/en-us/graph/api/intune-apps-macosdmgapp-create?view=graph-rest-beta) don´t support this property. 
[#microsoft.graph.macOSLobApp](https://learn.microsoft.com/en-us/graph/api/intune-apps-macoslobapp-create?view=graph-rest-beta) support this property, but not support #microsoft.graph.macOSIncludedApp, it have to be:

"childApps": [
    {
      "@odata.type": "microsoft.graph.macOSLobChildApp",
      "bundleId": "Bundle Id value",
      "buildNumber": "Build Number value",
      "versionNumber": "Version Number value"
    }
  ]

i think, the buildNumber was missing in the version before you change IntuneAppUploader.py

@almenscorner 

is it possible that you modify IntuneAppUploader to support?:
- dmg -> useful for DMG
- pkg unmanaged -> useful for unmanaged apps or apps that not installed under /Application
- pkg managed -> useful for managed apps and better assignment support

**Comment by drviper75** [comment]
Sorry, see you comments regarding managed apps. can be closed

**Comment by almenscorner** [comment]
You are right that DMG and unmanaged PKG that this processor supports has no support for the "install-as-managed" key.

I'm not entirely sure putting effort into adding support for LOB type apps will be worth it as all assignment options will be available for the other app types as well down the road. In my opinion the limitations with that kind outweigh the benefit.

**Comment by drviper75** [comment]
That's true, but the question is where is the development of macos going. if there are the same advantages in the future as with ios in terms of managed apps, i think that's valuable.
That with the effort to sign apk and so on, is correct.

I just thought a little further how your processor and autopkg would simplify the work in intune, already simplified it!

**Comment by almenscorner** [comment]
I'll think about it a bit and see how much effort it would be
